logging:
   level:
      web: DEBUG
      org.springframework.web: DEBUG

   file: expense-manager.log  
   
server:
#   port: 8090
   servlet:
      context-path: /expense-manager

spring:
   jpa:
      show-sql: true
#   datasource:
#      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      driverClassName: org.h2.Driver
#      username: sa